services:
  frontend-balls:
    image: ghcr.io/llstudent83/balls_js:latest
    expose:
      - '80'
    restart: unless-stopped
    networks:
      - priguli-apps

networks:
  priguli-apps:
    external: true
